name: Test

on:
  push:
    branches:
      - main

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        uses: mskelton/setup-yarn@v1.3.0
        
      - name: Coverage
        run: yarn coverage
